package uploadAndDownload;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class upload {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
//        options.setHeadless(false);
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        System.out.println("bredrttyhju==============");
    }

    @After
    public void tearDown() {
        // driver.quit();
    }

    @Test
    public void uplosad1() {
        driver.get("https://demoqa.com/upload-download");
        driver.findElement(By.id("uploadFile")).sendKeys("C:\\Users\\BISWARANJAN NAYAK\\Documents\\choice.cpp");
    }

    @Test
    public void uplosad2() {
        driver.get("https://demo.automationtesting.in/FileUpload.html");
        driver.manage().window().maximize();
        WebElement uploadFile = driver.findElement(By.id("input-4"));
        driver.findElement(By.id("input-4")).sendKeys("C:\\Users\\BISWARANJAN NAYAK\\Documents\\choice.cpp");
        //js.executeScript("window.scrollBy(0,1500)");
        js.executeScript("arguments[0].scrollIntoView()", driver.findElement(By.cssSelector(".btn.btn-default.fileinput-remove.fileinput-remove-button")));
        // driver.findElement(By.cssSelector(".btn.btn-default.fileinput-remove.fileinput-remove-button")).click();
    }

    @Test
    public void uplosad3_robot_class() throws AWTException {
        driver.get("https://demoqa.com/upload-download");
        driver.manage().window().maximize();
        WebElement uploadFile = driver.findElement(By.id("uploadFile"));
        //js.executeScript("arguments[0].click()",uploadFile);-------------js is not working for click in file upload.
        Actions act = new Actions(driver);
        act.moveToElement(uploadFile).click().build().perform();

        StringSelection cpystr = new StringSelection("C:\\Users\\BISWARANJAN NAYAK\\IdeaProjects\\GITHUB Repos\\selenium photo study\\testNG.xml");
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(cpystr, null);

//======================================= Robot class will not work in Headless mode ====================================================================
        Robot rb = new Robot();
        rb.setAutoDelay(5000);
        rb.keyPress(KeyEvent.VK_CONTROL);
        rb.keyPress(KeyEvent.VK_V);
        rb.keyRelease(KeyEvent.VK_CONTROL);
        rb.keyRelease(KeyEvent.VK_V);
        rb.keyPress(KeyEvent.VK_ENTER);
        rb.keyRelease(KeyEvent.VK_ENTER);

        System.out.println(driver.findElement(By.id("uploadedFilePath")).getText());
    }

    @Test
    public void AutoIT() throws IOException, InterruptedException {
        driver.get("https://the-internet.herokuapp.com/upload");
        WebElement uploadFile = driver.findElement(By.id("file-upload"));
        // uploadFile.click();------------not working for this but sometimes work
        //js.executeScript("arguments[0].click()",uploadFile);----------not working in this website
        Actions act = new Actions(driver);
        act.moveToElement(uploadFile).click().build().perform();
        Thread.sleep(5000);
        Runtime.getRuntime().exec("C://Users//BISWARANJAN NAYAK//Documents//fileUploadAutoItcode.exe" + " " + "\"C:\\Users\\BISWARANJAN NAYAK\\IdeaProjects\\Cucumber\\src\\main\\java\\page\\Github_page.java\"");
        Thread.sleep(5000);
        driver.findElement(By.id("file-submit")).click();

    }
}
